;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        meow-insert
        meow-insert-exit
        undo-fu-only-undo
        ))

(setq mc/cmds-to-run-once
      '(
        ))
